name: Build and Release Capacitor App

on:
  push:
    branches: [main]

jobs:
  version-bump:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bump minor version
        id: bump
        run: |
          CURRENT=$(node -p "require('./package.json').version")
          NEW=$(echo "$CURRENT" | awk -F. -v OFS=. '{$2++; $3=0; print}')
          echo "New version: $NEW"
          npm version $NEW --no-git-tag-version
          echo "version=$NEW" >> "$GITHUB_OUTPUT"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Bump version to $NEW"
          git push

  build-android:
    runs-on: ubuntu-latest
    needs: version-bump
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js and Android SDK
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Android APK
        run: |
          npm run build
          npx cap sync android
          cd android
          ./gradlew assembleRelease
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk

  build-ios:
    runs-on: macos-latest
    needs: version-bump
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build unsigned IPA
        run: |
          npm run build
          npx cap sync ios
          cd ios
          xcodebuild -scheme App -configuration Release -sdk iphoneos \
            -destination generic/platform=iOS \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            build

          mkdir Payload
          cp -r build/Release-iphoneos/*.app Payload/
          zip -r App.ipa Payload
        working-directory: ios/App

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/App/App.ipa

  release:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios, version-bump]
    steps:
      - uses: actions/checkout@v4

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: ./release

      - name: Download iOS IPA
        uses: actions/download-artifact@v4
        with:
          name: ios-ipa
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.version-bump.outputs.version }}
          name: Release v${{ needs.version-bump.outputs.version }}
          files: |
            release/*.apk
            release/*.ipa
