name: Build and Release Capacitor App

on:
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-latest
    outputs:
      datetime_tag: ${{ steps.timestamp.outputs.datetime_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Set time-based release tag (GMT -4)
        id: timestamp
        run: |
          export TZ=America/Puerto_Rico
          DATETIME=$(date +"%Y-%m-%d-%H-%M")
          echo "datetime_tag=$DATETIME" >> "$GITHUB_OUTPUT"

      - name: Build iOS and Manually Package IPA
        run: |
          npm run build
          npx cap sync ios
          cd ios/App
          pod install

          # Replace 'App' with your actual scheme name if different
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination generic/platform=iOS \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            build | tee xcodebuild.log

          echo "Finding built .app file..."
          APP_PATH=$(find /Users/runner/Library/Developer/Xcode/DerivedData/ -type d -name "*.app" | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "❌ No .app found after build"
            exit 1
          fi

          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -r "App-${{ steps.timestamp.outputs.datetime_tag }}.ipa" Payload

          mkdir -p release
          mv "App-${{ steps.timestamp.outputs.datetime_tag }}.ipa" release/

      - name: Show Xcode build log on failure
        if: failure()
        run: |
          echo "--- Last 100 lines of xcodebuild.log ---"
          tail -n 100 ios/App/xcodebuild.log || echo "Log not found"

      - uses: actions/upload-artifact@v4
        with:
          name: ios-artifact
          path: ios/App/release/*.ipa

  build-android:
    runs-on: ubuntu-latest
    needs: build-ios
    outputs:
      datetime_tag: ${{ needs.build-ios.outputs.datetime_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Build Android APK
        run: |
          npm run build
          npx cap sync android
          cd android
          ./gradlew assembleRelease

      - name: Debug APK output path
        run: find android/app/build/outputs -type f

      - name: Rename and upload APK artifact
        run: |
          mkdir -p release
          cp android/app/build/outputs/apk/release/app-release-unsigned.apk release/app-${{ needs.build-ios.outputs.datetime_tag }}.apk

      - uses: actions/upload-artifact@v4
        with:
          name: android-artifact
          path: release/*.apk

  release:
    runs-on: ubuntu-latest
    needs: [build-ios, build-android]
    steps:
      - uses: actions/checkout@v4

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: android-artifact
          path: release

      - name: Download IPA
        uses: actions/download-artifact@v4
        with:
          name: ios-artifact
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ needs.build-ios.outputs.datetime_tag }}
          name: Release ${{ needs.build-ios.outputs.datetime_tag }}
          files: |
            release/*.apk
            release/*.ipa
